services:
  db:
    image: postgres:16
    container_name: clean-hexapp-db
    restart: always
    environment:
      POSTGRES_USER: clean-hexuser
      POSTGRES_PASSWORD: clean-hexpass
      POSTGRES_DB: clean-hexapp
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
